
```{r message=FALSE}
library(curatedTCGAData)
library(TCGAutils)
library(maftools)
library(checkmate)
library(org.Hs.eg.db)
library(EDASeq)
library(impute)
library(doParallel)
library(MethylMix)
library(TCGAbiolinks)
library(MOSClip)
library(graphite)
```

## Prepare data for MOSClip analysis

```{r}
# load pre-processed data
load("../MOSresults/downloadTCGA/TCGA-OV-pre-processed.RData")
```

```{r}
survAnnotations <- fup$pfs

expression <- expAvg
row.names(expression) <- paste0("ENTREZID:", row.names(expression))
mutation <- ov.mutations$data
row.names(mutation) <- paste0("ENTREZID:", row.names(mutation))
names(metClustValues$eMap) <- paste0("ENTREZID:", row.names(metClustValues$eMap))
row.names(ov.cnv) <- paste0("ENTREZID:", row.names(ov.cnv))
```

```{r}
# select common patients (two-class)
survAnnot <- na.omit(survAnnotations)
patients <- row.names(classes)
patients <- intersect(patients, row.names(survAnnot))
patients <- intersect(patients, colnames(expression))
patients <- intersect(patients, colnames(metClustValues$MET_Cancer_Clustered))
patients <- intersect(patients, colnames(mutation))
patients <- intersect(patients, colnames(ov.cnv))

survAnnot <- survAnnot[patients, , drop=FALSE]
classAnnot <- classes[patients, , drop=FALSE]
table(classAnnot)
```


```{r}
# normalize expression data
expression <- expression[, patients, drop = F]
keep = apply(expression >= 100, 1, any)
expNorm <- betweenLaneNormalization(expression[keep, , drop = F], which = "upper")
pseudoExpNorm <- log2(expNorm + 1)

methylation <- metClustValues
methylation$MET_Cancer_Clustered <- methylation$MET_Cancer_Clustered[, patients, 
    drop = F]

mutation <- mutation[, patients, drop = F]
cnv <- ov.cnv[, patients, drop = F]
```

```{r}
multiOmics <- makeOmics(experiments = list(exp = pseudoExpNorm, 
                                           met = methylation$MET_Cancer_Clustered, 
                                           mut = mutation, 
                                           cnv = as.matrix(cnv)), 
                        colData = survAnnot,
    modelInfo = c("summarizeWithPca", "summarizeInCluster", 
    "summarizeToNumberOfEvents", "summarizeToNumberOfDirectionalEvents"), 
    specificArgs = list(pcaArgs = list(name = "exp", shrink = "FALSE", method = "sparse", maxPCs = 3),
                        clusterArgs = list(name = "met", dict = methylation$eMap, max_cluster_number = 3), 
                        countEvent = list(name = "mut", min_prop = 0.05), 
                        cnvAgv = list(name = "cnv", min_prop = 0.05)))
```

### Download Reactome pathways

```{r}
if (file.exists("reactome-entrez-2024-05-27.RData")) {
  load("reactome-entrez-2024-05-27.RData")
} else {
  reactome <- pathways("hsapiens", "reactome")
  reactome <- convertIdentifiers(reactome, "entrez")
  file = paste0(dirname, "/reactome-entrez-", as.character(Sys.Date()), ".RData")
  link = "reactome-entrez.RData"
  save(reactome, file = file)
  file.symlink(file, link)
}

nodesLength <- sapply(reactome, function(g) {length(intersect(graphite::nodes(g), row.names(pseudoExpNorm)))})
reactSmall <- reactome[nodesLength >= 20 & nodesLength <= 100]
reactHuge <- reactome[nodesLength >= 10]
```

### Prepare class annotations
Immunoreactive vs Mesenchymal

```{r}
class1 <- "Immunoreactive"
class2 <- "Mesenchymal"
classAnnotation <- classAnnot[classAnnot$classes %in% c(class1, class2), , drop=FALSE]
multiOmics <- multiOmics[,row.names(classAnnotation)]
```


## Two-class analysis on modules

```{r message=FALSE, warning=FALSE}
if (file.exists("twoClassM.rds")){
  twoClassM <- readRDS("twoClassM.rds")
} else { 
  system.time(twoClassM <- lapply(reactSmall, function(g) {
    res <- multiOmicsTwoClassModuleTest(multiOmics, g, classAnnotation, useTheseGenes = row.names(pseudoExpNorm))
    #print(g@title)
    res
    }))
  saveRDS(twoClassM, file="twoClassM.rds")
}

moduleSummary <- multiPathwayModuleReport(twoClassM)
moduleSummary
```

### Plots

```{r}
plotModuleReport(twoClassM[["Activation of Matrix Metalloproteinases"]])
```

```{r}
plotModuleInGraph(twoClassM[["Activation of Matrix Metalloproteinases"]], reactSmall, 3)
```


```{r}
plotModuleHeat(twoClassM[["Activation of Matrix Metalloproteinases"]], 3, additionalAnnotations = classAnnotation, 
               additionalPaletteNames = list(classes="violet"))
```

```{r}
runSupertest(multiPathwayModuleReport(twoClassM), pvalueThr = 0.05, zscoreThr = 0.05, excludeColumns = c("pathway", "module"))
```

```{r}
pathHierarchyGraph <-  igraph::graph_from_data_frame(d =downloadPathwayRelationFromReactome(), directed = TRUE)

omicsClasses2pathways <- computeOmicsIntersections(multiPathwayModuleReport(twoClassM), pvalueThr = 0.05, zscoreThr = 0.05, excludeColumns = c("pathway", "module"))
omicsClasses2pathways <- lapply(omicsClasses2pathways, stripModulesFromPathways)
omicsClasses2fathers <- lapply(omicsClasses2pathways, annotePathwayToFather, graphiteDB = reactome, hierarchy = pathHierarchyGraph)
correspondence <- lapply(names(omicsClasses2pathways), function(omicClass) {
  data.frame(path = omicsClasses2pathways[[omicClass]], father = omicsClasses2fathers[[omicClass]], 
             stringsAsFactors = F)})
MOMfreqDataframe <- computeFreqs(omicsClasses2fathers)
combiClass <- grep(";", MOMfreqDataframe$class)
MOMfreqDataframe.multi <- MOMfreqDataframe[combiClass, , drop = F]
colors <- c(`cnv;exp` = "#ff5722", `cnv;exp;met` = "#FFAB00", `cnv;met` = "#A5F037", 
            `cnv;mut` = "#30B30D", `exp;met` = "#6c5b07", `exp;mut` = "#A200AD", `met;mut` = "#01B7BF")

plotFrequencies(MOMfreqDataframe.multi, minSize = 6, maxSize = 8, width = 10, manualColors = colors, lineSize = 1)
```

### Permutations

```{r warning=FALSE, eval=FALSE}
moduleSummary <- multiPathwayModuleReport(twoClassM)

useThisPathways <- unique(moduleSummary$pathway[moduleSummary$pvalue <= 0.05])
sModule <- moduleSummary[moduleSummary$pathway %in% useThisPathways, , drop = T]

system.time(perms <- resamplingModulesTwoClass(fullMultiOmics = multiOmics, 
                                               classAnnotation, reactSmall, nperm = 100, 
                                               pathwaySubset = useThisPathways, 
                                               genesToConsider = row.names(pseudoExpNorm)))
save(perms, file="../MOSresults/permsM.RData")

stableModulesSummary <- selectStablePathwaysModules(perms = perms, moduleSummary = sModule, success = 80)
resamplingSuccessCount <- getPathwaysModulesSuccess(perms = perms, moduleSummary = sModule)
moduleSummary <- addResamplingCounts(moduleSummary, resamplingSuccessCount)
```

## Two-class analysis on pathways

```{r warning=FALSE, eval=FALSE}
multiOmics@specificArgs$pcaArgs$shrink=TRUE
multiOmics@specificArgs$pcaArgs$method="topological"

if (file.exists("twoClassP.rds")){
  twoClassP <- readRDS("twoClassP.rds")
} else {
  system.time(twoClassP <- lapply(reactHuge, function(g) {
    res <- multiOmicsTwoClassPathwayTest(multiOmics, g, classAnnotation, useTheseGenes = row.names(pseudoExpNorm))
    #print(g@title)
    res
  }))}

pathwaySummary <- multiPathwayReport(twoClassP)
```

```{r eval=FALSE}
save(twoClassM, twoClassP, file="twoClassSub_immmes.RData")
```

### Permutations

```{r warning=FALSE, eval=FALSE}
pathwaySummary <- multiPathwayReport(twoClassP)

useThisPathways <- unique(row.names(pathwaySummary)[pathwaySummary$pvalue <= 0.05])
sPathway <- pathwaySummary[row.names(pathwaySummary) %in% useThisPathways, , drop = T]

system.time(perms <- resamplingPathwayTwoClass(fullMultiOmics = multiOmics, 
                                                classAnnotation, reactHuge, nperm = 1, 
                                                pathwaySubset = useThisPathways, 
                                                genesToConsider = row.names(pseudoExpNorm)))
save(perms, file="../MOSresults/permsP.RData")

stablePathwaysSummary <- selectStablePathwaysModules(perms = perms, moduleSummary = sPathway, success = 80)
resamplingSuccessCount <- getPathwaysModulesSuccess(perms = perms, moduleSummary = sPathway)
pathwaySummary <- addResamplingCounts(pathwaySummary, resamplingSuccessCount)
```