# _config.yml

title: "MOSClip Tutorials"
description: "Tutorials series"
baseurl: ""  
url: "https://CaluraLab.github.io" 


theme: minima 

# Plugins (optional)
#plugins:
#  - jekyll-feed  # Example: Add an RSS feed for your site

# Additional Settings
markdown: kramdown  # The default Markdown engine used by Jekyll
#permalink: pretty  # Clean URLs without file extensions (optional)
