# _config.yml

title: "MOSClip Tutorials"
description: "Tutorial series"
baseurl: "/MOSClipTutorials"  
url: "https://caluralab.github.io" 


theme: jekyll-theme-cayman 


# Additional Settings
markdown: kramdown  
permalink: pretty  
